---
- hosts: app
  become: true  
  tasks:
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        state: "{{ state }}"
        update_cache: yes
      notify: Start Apache
      when: state == 'present'

    - name: Copy file with owner and permission
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
      notify: Restart Apache
      when: state == 'present'

  handlers:
    - name: Start Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted